version: '2'

services:

  registry:
    build: registry
    ports:
      - 8761:8761

  configserver:
    build: config-server
    ports:
      - 8888:8888
    environment:
      EUREKASERVER_URI: http://registry:8761/eureka/
      EUREKASERVER_PORT: 8761


  user-service:
    build: user-service
    ports:
      - 9002:9002
    environment:
      PROFILE: default
      CONFIGSERVER_URI: http://configserver:8888
      EUREKASERVER_URI: http://eurekaserver:8761/eureka/
      EUREKASERVER_PORT: 8761
      CONFIGSERVER_PORT: 8888

